const MachineData = [{
  id: 1,
  model: 'AK1',
  status: 0,
  temperature: 18,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 2,
  model: 'AK2',
  status: 1,
  temperature: 20,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 3,
  model: 'AK3',
  status: 2,
  temperature: 16,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 4,
  model: 'AK4',
  status: 0,
  temperature: 11,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 5,
  model: 'AK5',
  status: 1,
  temperature: 13,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 6,
  model: 'AK6',
  status: 2,
  temperature: 6,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 7,
  model: 'AK7',
  status: 0,
  temperature: 2,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 8,
  model: 'AK8',
  status: 1,
  temperature: 1,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 9,
  model: 'AK9',
  status: 2,
  temperature: 18,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 10,
  model: 'AK10',
  status: 0,
  temperature: 33,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 11,
  model: 'AK11',
  status: 1,
  temperature: 14,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 12,
  model: 'AK12',
  status: 2,
  temperature: 17,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 13,
  model: 'AK13',
  status: 0,
  temperature: 32,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 14,
  model: 'AK14',
  status: 1,
  temperature: 29,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 15,
  model: 'AK15',
  status: 2,
  temperature: 16,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 16,
  model: 'AK16',
  status: 0,
  temperature: 12,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 17,
  model: 'AK17',
  status: 1,
  temperature: 31,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 18,
  model: 'AK18',
  status: 2,
  temperature: 30,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 19,
  model: 'AK19',
  status: 0,
  temperature: 18,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}, {
  id: 20,
  model: 'AK20',
  status: 1,
  temperature: 19,
  address: 'No.98, Dayong Rd., Yancheng Dist., Kaohsiung City 803, Taiwan (R.O.C.)',
  region: 'Yancheng',
  disable: false,
}];

module.exports = MachineData;
